In [1]:
x = [[12, 3], [4, 5]]

In [2]:
x

[[12, 3], [4, 5]]

In [3]:
sum(x, [])

[12, 3, 4, 5]

In [17]:
x = {'a':2, 'b':54, 'c':15}
x.values()


dict_values([2, 54, 15])

In [18]:
sorted(x.items(), key=lambda x:x[1])

[('a', 2), ('c', 15), ('b', 54)]

In [20]:
sorted(x.items(), key=)

[('a', 2), ('b', 54), ('c', 15)]

In [23]:
sorted(x.items(), key=lambda x:x[1])[]

[('a', 2), ('c', 15), ('b', 54)]

In [25]:
dict(x.items())

{'a': 2, 'b': 54, 'c': 15}

In [26]:
x.items()

dict_items([('a', 2), ('b', 54), ('c', 15)])

In [27]:
dict([('a', 2), ('b', 54), ('c', 15)])

{'a': 2, 'b': 54, 'c': 15}

In [ ]:
Given n integer ranges, the task is to return the maximum occurring integer in the given ranges. If more than one such integer exists, return the smallest one.
The ranges are in two arrays l[] and r[].  l[i] consists of the starting point of the range and r[i] consists of the corresponding endpoint of the range & a maxx which is the maximum value of r[].

For example, consider the following ranges.
l[] = {2, 1, 3}, r[] = {5, 3, 9)
Ranges represented by the above arrays are.
[2, 5] = {2, 3, 4, 5}
[1, 3] = {1, 2, 3}
[3, 9] = {3, 4, 5, 6, 7, 8, 9}
The maximum occurred integer in these ranges is 3.
Example 1:

Input: n = 4, l[] = {1,4,3,1}, r[] = {15,8,5,4}, maxx = 15
Output: 4
Explanation: The given ranges are [1,15] [4, 8] [3, 5] [1, 4]. The smallest number that is most common or appears most times in the ranges is 4.
Example 2:

Input: n = 5, l[] = {1,5,9,13,21}, r[] = {15,8,12,20,30}, maxx = 30
Output: 5
Explanation: The given ranges are [1, 15] [5, 8] [9, 12] [13, 20] [21, 30]. The smallest number that is most common or appears most times in the ranges is 5.
Expected Time Complexity: O(n+maxx).
Expected Auxiliary Space: O(maxx), maxx is maximum element in r[]

Constraints:
1 ≤ n ≤ 106
0 ≤ l[i], r[i] ≤ 106

In [ ]:
10
2 5 3 4 3 3 2 7 9 6
4 5 6 6 8 3 10 10 10 10

In [ ]:
#User function Template for python3

class Solution:
    #Complete this function
    #Function to find the maximum occurred integer in all ranges.
    def maxOccured(self,n, l, r, maxx):
        ##Your code here
        n = n
        l = l
        r = r
        
        stack =[]
        final = []
        
        lst = [(l[i], r[i]) for i in range(n) ]
        lst = [(i[0], i[1]) for i in lst]
        for i, val in enumerate(lst):
            stack.append([i for i in range(val[0], val[1]+1)])
        
        stack = sum(stack, [])
        dict = {}
        for i in stack:
            if i not in dict:
                dict[i] = 1
            else:
                dict[i]=dict[i]+1
                
        dict = dict.items()
        
        dsbv = sorted(dict, key=lambda x:x[1])
        max_value = dsbv[-1][1]
        top_ranker = sorted([i for i in dsbv if i[1]==max_value])[0][0]
        
        # final_dict = dict([i for i in dsbv if i[1]==max_value])
        return top_ranker
        
        
            
        
        
        
            

#{ 
 # Driver Code Starts
#Initial Template for Python 3

import math

A = [0] * 1000000


def main():

    T = int(input())

    while (T > 0):

        global A
        A = [0] * 1000000

        n = int(input())

        l = [int(x) for x in input().strip().split()]
        r = [int(x) for x in input().strip().split()]

        maxx = max(r)
        ob = Solution()
        print(ob.maxOccured(n, l, r, maxx))

        T -= 1


if __name__ == "__main__':
    main()

# } Driver Code Ends

In [14]:
import numpy as np 
  
v = np.array([1, 2, 3])   
w = np.array([4, 5])     
  
# Outer product of vectors v and w
# print(np.reshape(v, (3,1)))
# print(np.reshape(v, (3, 1)) * w) 
  
x = np.array([[1, 2, 3], [4, 5, 6]])

print(x)
print(v)
print(x+v)




[[1 2 3]
 [4 5 6]]
[1 2 3]
[[2 4 6]
 [5 7 9]]


In [15]:
arr = [3, 4, 6, 9]
arr.index(4)


1

In [4]:
print(x+v)

[[2 4 6]
 [5 7 9]]


In [7]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

# print 'First array is:' 
print (a) 
# print '\n'  

# print 'Second array is:' 
b = np.array([1, 2, 3, 4], dtype = int) 
print(b)  
# print '\n' 

# print 'Modified array is:' 



[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[1 2 3 4]


In [9]:
[a,b]

[array([[ 0,  5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55]]),
 array([1, 2, 3, 4])]

In [8]:
for x,y in np.nditer([a,b]): 
   print('%d:%d' % (x,y))

0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [1]:
float('-inf')


-inf

In [5]:
lowest_path_cost = float('inf')
# pretend that these were calculated using some worthwhile algorithm
path_costs = [ 100, 2000000000000, 50, 2]
for path in path_costs:
    if path < lowest_path_cost:
        lowest_path_cost = path

lowest_path_cost


2

In [6]:
lowest_path_cost = float('-inf')
# pretend that these were calculated using some worthwhile algorithm
path_costs = [ 100, 2000000000000, 50, 2]
for path in path_costs:
    if path > lowest_path_cost:
        lowest_path_cost = path

lowest_path_cost

2000000000000

In [ ]:
class Solution:
    #Function to find the maximum occurred integer in all ranges.
    def maxOccured(self, n, l, r, maxx):
        i = 0
        #Adding 1 at (L[i])th index and subtracting 1 at (R[i]+1)th
        #index in the array.
        while (i < n):
            A[l[i]] += 1
            A[r[i] + 1] -= 1
            i += 1

        #Initialise maximum sum as arr[0] and index as -1.
        msum = A[0]
        ind = 0

        i = 1
        #Finding the prefix sum of the array.
        while (i <= maxx):
            #Finding the prefix sum at every index of the array.
            A[i] += A[i - 1]

            #Updating maximum sum if prefix sum at current index is greater
            #than value stored earlier as maximum sum.
            #Storing the index with maximum prefix sum.
            if msum < A[i]:
                msum = A[i]
                ind = i
            i += 1

        #returning the index with maximum prefix sum which is maximum
        #occuring element in the array.
        return ind

In [13]:
A=[0]*8
A[0] = 'Google'
A[1] = 'Amazon'
A[2] = 'Facebook'
A[3] = 'Amazon'
A[4] = 'Microsoft'
A[5] = 'IBM'
A[6] = 'Apple'
A[7] = 'Microsoft'

In [14]:
def earliest_coverage_time(A):
    all_comp = set(A)

    for i in range(len(A)):
        if set(A[:i])==all_comp:
            return i+1

In [15]:
earliest_coverage_time(A)

8

In [17]:
def earliest_coverage_time(A):
    all_comp = set(A)

    for i in range(len(A)):
        all_comp.discard(A[i])
        if len(all_comp)==0:
            return i+1
        # if set(A[:i])==all_comp:
        #     return i+1

In [18]:
earliest_coverage_time(A)

7

In [19]:
A

['Google',
 'Amazon',
 'Facebook',
 'Amazon',
 'Microsoft',
 'IBM',
 'Apple',
 'Microsoft']

In [20]:
set(A)

{'Amazon', 'Apple', 'Facebook', 'Google', 'IBM', 'Microsoft'}

In [55]:
A = [64,99, 5, 3,  25, 12, 22, 11]


In [30]:

for i in range(len(A)-1):
    for j in range(i+1, len(A)):
        if A[i]>A[j]:
            A[i], A[j]= A[j], A[i]
            print(A)
        
    

[3, 99, 64, 5, 25, 12, 22, 11]
[3, 64, 99, 5, 25, 12, 22, 11]
[3, 5, 99, 64, 25, 12, 22, 11]
[3, 5, 64, 99, 25, 12, 22, 11]
[3, 5, 25, 99, 64, 12, 22, 11]
[3, 5, 12, 99, 64, 25, 22, 11]
[3, 5, 11, 99, 64, 25, 22, 12]
[3, 5, 11, 64, 99, 25, 22, 12]
[3, 5, 11, 25, 99, 64, 22, 12]
[3, 5, 11, 22, 99, 64, 25, 12]
[3, 5, 11, 12, 99, 64, 25, 22]
[3, 5, 11, 12, 64, 99, 25, 22]
[3, 5, 11, 12, 25, 99, 64, 22]
[3, 5, 11, 12, 22, 99, 64, 25]
[3, 5, 11, 12, 22, 64, 99, 25]
[3, 5, 11, 12, 22, 25, 99, 64]
[3, 5, 11, 12, 22, 25, 64, 99]


In [39]:
A

[64, 99, 5, 3, 25, 12, 22, 11]

In [56]:
for i in range(len(A)):
    for j in range(i+1, len(A)):
        if A[i]<A[j]:
            print(A)
            A[i], A[j]= A[j], A[i]

# print(A)

[64, 99, 5, 3, 25, 12, 22, 11]
[99, 64, 5, 3, 25, 12, 22, 11]
[99, 64, 25, 3, 5, 12, 22, 11]
[99, 64, 25, 5, 3, 12, 22, 11]
[99, 64, 25, 12, 3, 5, 22, 11]
[99, 64, 25, 22, 3, 5, 12, 11]
[99, 64, 25, 22, 5, 3, 12, 11]
[99, 64, 25, 22, 12, 3, 5, 11]
[99, 64, 25, 22, 12, 5, 3, 11]
[99, 64, 25, 22, 12, 11, 3, 5]


In [44]:
for i in range(len(A)-1):
    
    # Find the minimum element in remaining 
    # unsorted array
    min_idx = i
    for j in range(i+1, len(A)):
        if A[min_idx] > A[j]:
            print(i, min_idx, j, A)
            min_idx = j
            
    # Swap the found minimum element with 
    # the first element        
    A[i], A[min_idx] = A[min_idx], A[i]
    # print(A)

# Driver code to test above
print ("Sorted array")
# for i in range(len(A)):
#     print(A[i],end=" ") 

0 0 2 [64, 99, 5, 3, 25, 12, 22, 11]
0 2 3 [64, 99, 5, 3, 25, 12, 22, 11]
1 1 2 [3, 99, 5, 64, 25, 12, 22, 11]
2 2 3 [3, 5, 99, 64, 25, 12, 22, 11]
2 3 4 [3, 5, 99, 64, 25, 12, 22, 11]
2 4 5 [3, 5, 99, 64, 25, 12, 22, 11]
2 5 7 [3, 5, 99, 64, 25, 12, 22, 11]
3 3 4 [3, 5, 11, 64, 25, 12, 22, 99]
3 4 5 [3, 5, 11, 64, 25, 12, 22, 99]
4 4 6 [3, 5, 11, 12, 25, 64, 22, 99]
5 5 6 [3, 5, 11, 12, 22, 64, 25, 99]
Sorted array


In [57]:
a

NameError: name 'a' is not defined

In [76]:
A =[64, 99, 5, 3, 25, 12, 22, 11,980,1]
print("A ", A)
for i in range(len(A)):
    idx = i
    for j in range(i, len(A)):
        if A[idx]>A[j]:
            print("j ",j)
            idx=j
    A[i], A[idx]=A[idx], A[i]
    print(f"SWAPPED, {i} with {idx}", A)

A


A  [64, 99, 5, 3, 25, 12, 22, 11, 980, 1]
j  2
j  3
j  9
SWAPPED, 0 with 9 [1, 99, 5, 3, 25, 12, 22, 11, 980, 64]
j  2
j  3
SWAPPED, 1 with 3 [1, 3, 5, 99, 25, 12, 22, 11, 980, 64]
SWAPPED, 2 with 2 [1, 3, 5, 99, 25, 12, 22, 11, 980, 64]
j  4
j  5
j  7
SWAPPED, 3 with 7 [1, 3, 5, 11, 25, 12, 22, 99, 980, 64]
j  5
SWAPPED, 4 with 5 [1, 3, 5, 11, 12, 25, 22, 99, 980, 64]
j  6
SWAPPED, 5 with 6 [1, 3, 5, 11, 12, 22, 25, 99, 980, 64]
SWAPPED, 6 with 6 [1, 3, 5, 11, 12, 22, 25, 99, 980, 64]
j  9
SWAPPED, 7 with 9 [1, 3, 5, 11, 12, 22, 25, 64, 980, 99]
j  9
SWAPPED, 8 with 9 [1, 3, 5, 11, 12, 22, 25, 64, 99, 980]
SWAPPED, 9 with 9 [1, 3, 5, 11, 12, 22, 25, 64, 99, 980]


[1, 3, 5, 11, 12, 22, 25, 64, 99, 980]

In [3]:
sum([1,2])

3

In [7]:
4%2

0

In [5]:
5/2

2.5

In [8]:
3//2

1

In [16]:
a= [1, 2,9 ,3]
b =[2, 3]
a.extend(b)

In [13]:
a.sort()

In [17]:
a

[1, 2, 9, 3, 2, 3]

In [3]:
s = 'babad'
s = [i for i in s]
b = [2, 3, 4]

[s.append(i) for i in b]
s

['b', 'a', 'b', 'a', 'd', 2, 3, 4]

In [4]:
s.append(9)

In [6]:
s=['bab', 'aba']
print(s[0])

bab


In [7]:
class Solution:
    def longestPalindrome(self, s: str) -> str:
        s = [i for i in s]
        a = len(s)
        # print(s)
        collect = []
        for i in range(1, len(s) - 1):
            left = i
            right = i
            ls = i
            rs = i
            while s[left - 1] == s[right + 1] and left > 0:
                left = left - 1
                right += 1
                print(i, left, right)
                word = "".join(s[left : right + 1])
                collect.append(word)
            while s[ls] == s[rs + 1]:
                rs += 1
                word = "".join(s[ls: (rs + 1)])
                collect.append(word)
        return collect[0]
        

In [2]:
a = 'India'
score = 98

print("the country on top is  with (?,?))", (a, score))

the country on top is  with (?,?)) ('India', 98)
